// AUTO-GENERATED by scripts/generate-leaderboard-credentials.mjs
// Do not edit by hand. Regenerate with: node scripts/generate-leaderboard-credentials.mjs

import { createHash, timingSafeEqual } from "node:crypto";

/** Open tracks with a DB-backed leaderboard editor (excludes devops, low-latency, cybersec). */
export const EDITABLE_LEADERBOARD_SLUGS = [
  "genai-agentic",
  "autonomous-control-system",
  "quant",
  "consult",
  "analytics",
  "product",
  "computer-vision",
  "ml-in-proteins",
  "ml-astronomy",
  "competitive-programming",
  "gamedev",
  "defi-builder-cohort",
] as const;

export type EditableLeaderboardSlug = (typeof EDITABLE_LEADERBOARD_SLUGS)[number];

const EXCLUDED_EDITOR_SLUGS = new Set([
  "devops",
  "low-latency",
  "cybersec",
]);

type CredentialRecord = { username: string; passwordHash: string };

const CREDENTIALS: Record<EditableLeaderboardSlug, CredentialRecord> = {
  "genai-agentic": { username: "csot-genai-agentic", passwordHash: "2439a5644fb95774a99cdf61506964d05fd26b91f5a4025979dd6e379ba07489" },
  "autonomous-control-system": { username: "csot-autonomous-control-system", passwordHash: "e845350559bcf4f3a479201e24e2b580ef107614b00abbcfa02b9cf5bf250784" },
  "quant": { username: "csot-quant", passwordHash: "88e3a495cef087087a5b7e0cf137bf024bf94b94e135cd0f095a59a7be021e50" },
  "consult": { username: "csot-consult", passwordHash: "24296255ea768a91f6d7fc8691f874a5ecf0d828446991c20cc04c2fdff44973" },
  "analytics": { username: "csot-analytics", passwordHash: "e7c9c8e0bf8aa10ca7ad2c4a6089575ec0e7a04136d6cef3bf34af6386b491e6" },
  "product": { username: "csot-product", passwordHash: "56597bb8d6424301b5eda7de2d726aea060d2c44bb57bbf445e07638c223c31e" },
  "computer-vision": { username: "csot-computer-vision", passwordHash: "e80a3da9d78d3c58fa9fa50bb2224f56e53e9b7025313f2440205caaaedfce82" },
  "ml-in-proteins": { username: "csot-ml-in-proteins", passwordHash: "82313cddd8fc93d788b86c1a164aa712bfa7774edbb7a1736cf0627f7dc8cd68" },
  "ml-astronomy": { username: "csot-ml-astronomy", passwordHash: "6e17119a8abed88f5085873835933f526f8f7ec73aa13a1944aff481484a7c56" },
  "competitive-programming": { username: "csot-competitive-programming", passwordHash: "6648ddfbf2ebf10a2f97dca025875b05c8ad8b55b3292a9653fcb2754d945483" },
  "gamedev": { username: "csot-gamedev", passwordHash: "cb63896298e0aeab1b1d2218b61767f393d4e0abc3599628dc4a9fc6f711982c" },
  "defi-builder-cohort": { username: "csot-defi-builder-cohort", passwordHash: "da0835c7bd5f9a91627f997ac7c43553e22aeee8c2f796aee1e3e549e8f8ba41" },
};

function hashPassword(slug: string, password: string): string {
  return createHash("sha256")
    .update(`csot-lb-editor:${slug}:${password}`)
    .digest("hex");
}

export function isEditableLeaderboardSlug(
  slug: string,
): slug is EditableLeaderboardSlug {
  return (
    (EDITABLE_LEADERBOARD_SLUGS as readonly string[]).includes(slug) &&
    !EXCLUDED_EDITOR_SLUGS.has(slug)
  );
}

export function verifyEditorCredentials(
  slug: EditableLeaderboardSlug,
  username: string,
  password: string,
): boolean {
  const record = CREDENTIALS[slug];
  if (!record) return false;
  if (record.username !== username.trim()) return false;
  const got = hashPassword(slug, password);
  const expected = record.passwordHash;
  if (got.length !== expected.length) return false;
  return timingSafeEqual(Buffer.from(got), Buffer.from(expected));
}

export function getEditorUsername(slug: EditableLeaderboardSlug): string {
  return CREDENTIALS[slug].username;
}
